import { useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import { ChevronDown, MessageCircle, ShieldCheck, Sparkles, Snowflake, MonitorPlay, BatteryCharging, Armchair, Headphones, SprayCan, CalendarDays, Phone, MapPin, Clock3, ArrowRight, CheckCircle2 } from 'lucide-react';
import { servicePages } from '../data/servicePages';
import { whatsapp, phone } from '../data/siteData';
import './ServiceLanding.css';
const featureIcons=[Snowflake,MonitorPlay,BatteryCharging,Armchair,Headphones,SprayCan];
const defaultTrips=[['Tirumala Darshan','Tirupati → Tirumala','Temple visit · Same day'],['Srikalahasti Temple','Tirupati → Srikalahasti','Pilgrimage · Same day'],['Kanipakam Temple','Tirupati → Kanipakam','Pilgrimage · Same day'],['Golden Temple','Tirupati → Vellore','Temple tour · Same day'],['Kanchipuram','Tirupati → Kanchipuram','Temple circuit · Same day'],['Pondicherry','Tirupati → Pondicherry','Sightseeing · 1–2 days']];
const tripMap={
 'car-rentals-in-tirupati':defaultTrips,'tempo-traveller-rental-in-tirupati':defaultTrips,'urbania-traveller-rental-in-tirupati':defaultTrips,
 'bus-rental-in-tirupati':[['Tirupati Temple Circuit','Tirupati → Tirumala','Group pilgrimage · 1 day'],['Srikalahasti & Kanipakam','Tirupati → Srikalahasti → Kanipakam','Temple tour · 1 day'],['Kanchipuram Tour','Tirupati → Kanchipuram','Group pilgrimage · 1 day'],['Arunachalam Tour','Tirupati → Arunachalam','Pilgrimage · 2 days'],['Pondicherry Tour','Tirupati → Pondicherry','Group sightseeing · 2 days'],['South India Temple Tour','Multi-city route','Custom multi-day group trip']],
 'outstation-taxi-in-tirupati':[['Srikalahasti','Tirupati → Srikalahasti','Temple trip · Same day'],['Kanipakam','Tirupati → Kanipakam','Temple trip · Same day'],['Golden Temple','Tirupati → Vellore','Temple trip · Same day'],['Kanchipuram','Tirupati → Kanchipuram','Temple circuit · Same day'],['Madurai','Tirupati → Madurai','Pilgrimage · Multi-day'],['Srisailam','Tirupati → Srisailam','Pilgrimage · Multi-day']],
 'taxi-in-tirupati':defaultTrips,
 'tirupati-airport-taxi':[['Tirupati Airport → Tirupati','Airport → Hotel / City','Pickup · 30–40 min'],['Tirupati Airport → Tirumala','Airport → Tirumala','Temple transfer'],['Airport → Railway Station','Airport → Tirupati Railway Station','Transfer service'],['Airport → Srikalahasti','Airport → Srikalahasti','Temple transfer'],['Airport → Kanipakam','Airport → Kanipakam','Temple transfer'],['Airport → Vellore','Airport → Golden Temple','Outstation transfer']],
 'car-for-rent-in-tirupati-day-rentals':defaultTrips};
export default function ServiceLanding({slug:routeSlug}){const params=useParams();const slug=routeSlug||params.slug;const data=servicePages[slug];const [open,setOpen]=useState(null);if(!data)return <main className="service-page content"><h1>Service not found</h1><Link to="/services">Back to Services</Link></main>;const booking=`${whatsapp}?text=${encodeURIComponent(`Hi, I am interested in ${data.title}. Please share availability and the current trip price.`)}`;const trips=tripMap[slug]||defaultTrips;return <main className="service-page">
<section className="service-hero"><div className="service-hero-copy"><span className="eyebrow">{data.eyebrow}</span><h1>{data.title}</h1><p>{data.intro}</p><div className="service-actions"><a className="button" href={`tel:${phone}`}><Phone/> Call Now</a><a className="button" href={booking} target="_blank" rel="noreferrer"><MessageCircle/> WhatsApp</a></div></div><div className="service-hero-image"><img src={data.image} alt={data.title}/></div></section>
<section className="service-quick"><div><MapPin/><span><b>Local & outstation</b><small>Flexible pickup and routes</small></span></div><div><Clock3/><span><b>24×7 support</b><small>Travel assistance when needed</small></span></div><div><ShieldCheck/><span><b>Experienced drivers</b><small>Familiar with temple routes</small></span></div><a href={booking} target="_blank" rel="noreferrer" className="button">Get Trip Price <ArrowRight/></a></section>
<section className="content service-section service-about"><div className="section-heading"><span className="eyebrow">ABOUT THE SERVICE</span><h2>Travel around Tirupati with a plan that fits you.</h2><p>{data.intro} Whether you need a short temple transfer, a full-day sightseeing plan or a multi-day South India journey, choose the vehicle size and route that match your group.</p></div><div className="service-about-points"><div><CheckCircle2/><span>Pickup from airport, railway station, hotel or agreed location</span></div><div><CheckCircle2/><span>Local temple visits and customized outstation itineraries</span></div><div><CheckCircle2/><span>Vehicle options for families, groups and corporate travel</span></div></div></section>
<section className="content service-section"><div className="section-heading"><span className="eyebrow">WHY CHOOSE US</span><h2>{data.whyTitle||'A practical travel service, built around your trip.'}</h2>{data.whyIntro&&<p>{data.whyIntro}</p>}</div><div className="service-highlights">{data.highlights.map(x=><div key={x}><ShieldCheck/><span>{x}</span></div>)}</div></section>
{data.featureDetails&&<section className="service-section service-soft"><div className="content"><div className="section-heading"><span className="eyebrow">TOP FEATURES</span><h2>Comfort, convenience and a better group journey.</h2><p>Explore the features available across the published vehicle options.</p></div><div className="service-feature-grid">{data.featureDetails.map((x,i)=>{const Icon=featureIcons[i%featureIcons.length];return <article key={x[0]}><Icon/><h3>{x[0]}</h3><p>{x[1]}</p></article>})}</div></div></section>}
<section className="service-section service-soft"><div className="content"><div className="section-heading"><span className="eyebrow">VEHICLE OPTIONS & PRICING</span><h2>Choose what fits your journey.</h2><p>{data.outstation}</p></div><div className="service-vehicles">{data.vehicles.map(([name,capacity,price])=><article key={name}><div><Sparkles/><h3>{name}</h3><p>{capacity}</p></div><strong>{price}</strong><a href={booking} target="_blank" rel="noreferrer">Ask availability <ArrowRight/></a></article>)}</div></div></section>
<section className="content service-section"><div className="section-heading"><span className="eyebrow">POPULAR TRIPS</span><h2>Trips customers can plan from Tirupati.</h2><p>Choose a route below or send us your own itinerary for a current trip price.</p></div><div className="service-trip-grid">{trips.map(([title,route,meta])=><article key={title}><div className="trip-icon"><MapPin/></div><small>{meta}</small><h3>{title}</h3><p>{route}</p><a href={booking} target="_blank" rel="noreferrer">Plan this trip <ArrowRight/></a></article>)}</div></section>
<section className="service-section service-soft"><div className="content"><div className="section-heading"><span className="eyebrow">WHAT YOU GET</span><h2>A straightforward booking experience.</h2></div><div className="service-included"><div><h3>Included / arranged</h3><p>Vehicle and driver for the confirmed itinerary, pickup and drop as agreed, and trip coordination through our booking team.</p></div><div><h3>Usually additional</h3><p>Tolls, parking, entry tickets, permits and other route-specific charges may apply. Confirm the final price before travel.</p></div><div><h3>Before departure</h3><p>Share date, pickup point, destination, passenger count and preferred vehicle so the team can confirm availability and current pricing.</p></div></div></div></section>
{data.packageNote&&<section className="content service-section service-package"><div className="service-package-card"><CalendarDays/><div><span className="eyebrow">LOCAL & OUTSTATION PACKAGES</span><h2>Plan the journey around your group.</h2><p>{data.packageNote}</p></div><a className="button" href={booking} target="_blank" rel="noreferrer"><MessageCircle/> Get Trip Price</a></div></section>}
<section className="content service-section"><div className="section-heading"><span className="eyebrow">HOW IT WORKS</span><h2>Simple from enquiry to departure.</h2></div><div className="service-steps">{data.steps.map((x,i)=><div key={x}><b>0{i+1}</b><span>{x}</span></div>)}</div></section>
<section className="content service-section service-tips"><div className="section-heading"><span className="eyebrow">TRAVEL TIPS</span><h2>Make your Tirupati trip smoother.</h2></div><div className="tips-grid"><p><b>Start early:</b> Early departures can help you fit temple visits and sightseeing into the day.</p><p><b>Share your plan:</b> Send your route and group size before booking so the right vehicle can be selected.</p><p><b>Keep darshan timing in mind:</b> Build enough time around temple entry and local traffic.</p></div></section>
<section className="content service-section"><div className="section-heading"><span className="eyebrow">FAQ</span><h2>Before you book.</h2></div><div className="service-faq">{data.faqs.map(([q,a],i)=><div className={open===i?'open':''} key={q}><button onClick={()=>setOpen(open===i?null:i)}>{q}<ChevronDown/></button>{open===i&&<p>{a}</p>}</div>)}</div></section>
<section className="service-final"><div><span className="eyebrow">READY WHEN YOU ARE</span><h2>Know your route? Let's plan it.</h2><p>Share your date, pickup, destination, group size and preferred vehicle. We'll help you check availability and the current trip price.</p><div className="service-actions"><a className="button" href={`tel:${phone}`}><Phone/> Call Now</a><a className="button" href={booking} target="_blank" rel="noreferrer"><MessageCircle/> WhatsApp</a></div></div></section></main>;}