import {motion} from 'framer-motion';
import {ArrowRight,MessageCircle,Phone} from 'lucide-react';
import {Link} from 'react-router-dom';
import './PopularPackages.css';

const packages=[
['2 Days Arunachalam Package','2 Days','Tirupati → Tiruttani → Kanchipuram → Arunachalam → Vellore → Kanipakam → Tirupati','https://tirupatibalajitourstravels.com/wp-content/uploads/2025/06/Arunachalam.png','https://tirupatibalajitourstravels.com/tour/tirupati-to-arunachalam-packages/'],
['1 Day Arunachalam Package','1 Day','Tirupati → Kanipakam → Golden Temple → Arunachalam → Tirupati','https://tirupatibalajitourstravels.com/wp-content/uploads/2025/09/ArunachalaShiva.webp','https://tirupatibalajitourstravels.com/tour/tirupati-to-arunachalam-taxi-service/'],
['Pancha Linga Tour from Tirupati','3 Days','Tirupati → Srikalahasti → Kanchipuram → Chidambaram → Srirangam → Arunachalam → Vellore → Kanipakam → Tirupati','https://tirupatibalajitourstravels.com/wp-content/uploads/2025/07/Pancha-Linga-Tour-from-Tirupati.png','https://tirupatibalajitourstravels.com/tour/pancha-linga-tour-from-tirupati/'],
['4 Days Tirupati Temple Tour Package – South India Pilgrimage Tour','4 Days','Tirupati → Tirumala → Kanipakam → Vellore → Arunachalam → Kanchipuram → Tiruttani → Srikalahasti → Tirupati','https://tirupatibalajitourstravels.com/storage/elementor/thumbs/4-days-tirupati-temple-tour-package-raiw174b87rbesrg385jxommx7lwf38ven8jnzp6wg.jpg','https://tirupatibalajitourstravels.com/tour/4-days-tirupati-temple-tour-package/'],
['Tirupati 1 Day Taxi Package','1 Day','Tirupati → Padmavathi → Tirumala → Varahaswamy → Balaji Darshan → Kapila Theertham → Tirupati','https://tirupatibalajitourstravels.com/wp-content/uploads/2025/07/Tirumala.png','https://tirupatibalajitourstravels.com/tour/tirupati-to-tirumala-taxi-service/'],
['Tirupati 2 Days Taxi Package','2 Days','Tirupati → Tirumala → Balaji Darshan → Kapila Theertham → ISKCON → Govindaraja → Padmavathi → Srikalahasti → Tirupati','https://tirupatibalajitourstravels.com/wp-content/uploads/2025/07/Tirumala-2.png','https://tirupatibalajitourstravels.com/tour/tirupati-2-days-taxi-package/'],
['Tirupati to Golden Temple Vellore Tour','1 Day','Tirupati → Srinivasa Mangapuram → Kanipakam → Golden Temple → Tirupati','https://tirupatibalajitourstravels.com/wp-content/uploads/2025/06/Vellore-Golden-Temple-1-1.jpg','https://tirupatibalajitourstravels.com/tour/tirupati-to-golden-temple-vellore-taxi-service/'],
['Tirupati to Kanipakam Temple Tour','1 Day','Tirupati → Vakula Devi → Srinivasa Mangapuram → Kanipakam → Tirupati','https://tirupatibalajitourstravels.com/wp-content/uploads/2025/06/kanipakam-1.jpg','https://tirupatibalajitourstravels.com/tour/tirupati-to-kanipakam-taxi-service/'],
['Tirupati 5 Local Temples Tour Package','1 Day','Tirupati → Kapila Theertham → ISKCON → Govindaraja Swamy → Padmavathi → Srikalahasti → Tirupati','https://tirupatibalajitourstravels.com/wp-content/uploads/2025/07/Tirumala-1.png','https://tirupatibalajitourstravels.com/tour/tirupati-5-local-temples-taxi-service/'],
['Tirupati to Kanchipuram Taxi Service','1 Day','Tirupati → Tiruttani → Kanchipuram → Varadaraja Perumal Temple → Kamakshi Amman Temple → Kailasanathar Temple → Tirupati','https://tirupatibalajitourstravels.com/storage/2025/06/Kachipuram.png','https://tirupatibalajitourstravels.com/tour/tirupati-to-kanchipuram-taxi-service/'],
['Tirupati to Mahabalipuram Taxi Service','2 Days','Tirupati → Kanchipuram → Kailasanathar Temple → Vaikunta Perumal Temple → Mahabalipuram Beach → Pancha Rathas → Arjuna’s Penance → Shore Temple → Tirupati','https://tirupatibalajitourstravels.com/storage/2025/06/Mahabalipuram.png','https://tirupatibalajitourstravels.com/tour/tirupati-to-mahabalipuram-taxi-service/'],
['Divine 5 Day South India Temple Tour Package','5 Days','Tirupati → Tirumala → Srinivasa Mangapuram → Kanipakam → Golden Temple (Vellore) → Arunachalam → Srirangam → Kanchipuram → Tiruttani → Tirupati → Srikalahasti → Tirupati','https://tirupatibalajitourstravels.com/storage/2025/07/South-India-Temple-Tour.png','https://tirupatibalajitourstravels.com/tour/south-india-temple-tour/'],
['Tirupati to Golden Temple Arunachalam Kanchipuram Taxi Service','2 Days','Tirupati → Kanipakam → Vellore → Arunachalam → Kanchipuram → Tiruttani → Tirupati','https://tirupatibalajitourstravels.com/storage/2025/02/Arunachalam-Temple-Complete-Guide-How-to-Reach-Timings.jpg','https://tirupatibalajitourstravels.com/tour/tirupati-to-golden-temple-arunachalam-kanchipuram-taxi-service-2/'],
['2 Days Tirupati to Madurai Tour Package','2 Days','Tirupati → Madurai → Meenakshi Amman Temple → Madurai Sightseeing → Tirupati','https://tirupatibalajitourstravels.com/storage/2025/07/Madurai.png','https://tirupatibalajitourstravels.com/tour/2-days-tirupati-to-madurai/'],
['Pondicherry Tour Package','2 Days','Tirupati → Pondicherry → Promenade Beach → Rock Beach → French Colony → Paradise Beach → Auroville → Pondicherry Sightseeing → Tirupati','https://tirupatibalajitourstravels.com/storage/2026/03/Pondicherry.png','https://tirupatibalajitourstravels.com/tour/pondicherry-tour-packages/'],
['2 Days Tirupati to Srisailam Taxi Package','2 Days','Tirupati → Srisailam → Mallikarjuna Swamy Temple → Bhramaramba Devi Temple → Srisailam Dam → Akkamahadevi Caves → Paladhara Panchadhara → Tirupati','https://tirupatibalajitourstravels.com/storage/elementor/thumbs/2-Days-Tirupati-to-Srisailam-Taxi-Package-r92ug9ilj9964f53y49h3bausjitrkz3btvlnk3i3w.jpg','https://tirupatibalajitourstravels.com/tour/2-days-tirupati-to-srisailam-taxi-package/'],
['3 Days Tirupati to Madurai Taxi Tour Package','3 Days','Tirupati → Arunachalam → Srirangam → Madurai → Tirupati','https://tirupatibalajitourstravels.com/storage/2025/06/Madurai.png','https://tirupatibalajitourstravels.com/tour/tirupati-to-madurai-taxi/'],
['4 Days Tirupati to Madurai Meenakshi Temple Tour Package','4 Days','Tirupati → Arunachalam → Srirangam → Madurai → Rameswaram → Tirupati','https://tirupatibalajitourstravels.com/storage/elementor/thumbs/Meenakshi-Amman-Temple-1-r8xrl29603chlkkhrffpsfohrikusasuxlie6rvub4.png','https://tirupatibalajitourstravels.com/tour/4-days-tirupati-to-madurai-meenakshi-temple-distance-tour-package/'],
['3 Days Tirupati Pondicherry via Kanchipuram Tour Package','3 Days','Tirupati → Tiruttani → Kanchipuram → Pondicherry → Auroville → Tirupati','https://tirupatibalajitourstravels.com/storage/2025/08/tirupati-to-pondicherry-distance-cab.webp','https://tirupatibalajitourstravels.com/tour/3-days-tirupati-pondicherry-tour-package/'],
['3 Days Tirupati Kanchipuram Temple Tour Package','3 Days','Tirupati → Tirumala → Tiruttani → Kanchipuram → Tirupati → Srikalahasti → Tirupati','https://tirupatibalajitourstravels.com/wp-content/uploads/2025/02/varadaraja-perumal-temple.jpg','https://tirupatibalajitourstravels.com/tour/3-days-tirupati-kanchipuram-temple-tour-package/'],
['3 Days Tirupati Srisailam Srikalahasti Taxi Package','3 Days','Tirupati → Srikalahasti → Srisailam → Tirupati','https://tirupatibalajitourstravels.com/storage/elementor/thumbs/Srisailam-r92ug6p2yr59xe7qy0q1o7go6r79ujcfd16vhr0sa8.jpg','https://tirupatibalajitourstravels.com/tour/3-days-tirupati-srisailam-srikalahasti-taxi-package/'],
['3 Days Tirupati Golden Temple Taxi Package','3 Days','Tirupati → Tirumala → Srinivasa Mangapuram → Kanipakam → Vellore → Tirupati → Srikalahasti → Tirupati','https://tirupatibalajitourstravels.com/storage/2025/07/Tirumala-3.png','https://tirupatibalajitourstravels.com/tour/3-days-tirupati-golden-temple-package/'],
['Best 5 Day Tirupati Arunachalam Mahabalipuram Tour Package','5 Days','Tirupati → Tirumala → Kanipakam → Vellore → Arunachalam → Mahabalipuram → Kanchipuram → Tiruttani → Tirupati → Srikalahasti → Tirupati','https://tirupatibalajitourstravels.com/storage/elementor/thumbs/Discover-the-8th-century-world-heritage-site-famous-for-spectacular-rock-cut-architecture-in-our-World-Heritage-Site-of-Mahabalipuram-scaled-1-r1ox1aiz1b095x8wdqe9t52sda5n9xy3p36bqmh4c0.jpg','https://tirupatibalajitourstravels.com/tour/tirupati-arunachalam-mahabalipuram-tour-package/'],
['7 Days Divine Tamil Nadu Temple Tour from Tirupati','7 Days','Tirupati → Vellore → Arunachalam → Srirangam → Madurai → Trivandrum → Kanyakumari → Rameswaram → Kumbakonam → Chidambaram → Kanchipuram → Tirupati','https://tirupatibalajitourstravels.com/storage/2025/07/Tamil-Nadu-Temple-Tour-from-Tirupati.png','https://tirupatibalajitourstravels.com/tour/7-day-divine-tamil-nadu-temple-tour-from-tirupati/']
];
export default function PopularPackages(){return <section className="popular-packages-section"><div className="popular-heading"><div><p className="eyebrow">🔥 MOST BOOKED PACKAGES</p><h2>Explore Our Popular Temple Tour Packages</h2><p>Safe, Comfortable & Memorable Journeys to Sacred Destinations</p></div><div className="popular-benefits"><span>🚕 Tolls Included</span><span>🅿️ Parkings Included</span><span>👨‍✈️ Driver Batta Included</span><span>🏛️ TN Border Tax Included</span><span>📞 24×7 Support</span><span>💰 Best Price Guaranteed</span></div></div><div className="popular-package-grid">{packages.map(([name,duration,route,image,details],i)=><motion.article className="popular-package-card" key={name} initial={{opacity:0,y:24}} whileInView={{opacity:1,y:0}} viewport={{once:true,amount:.1}} transition={{duration:.4,delay:(i%3)*.05}}><div className="popular-package-image"><img src={image} alt={name} loading="lazy"/><span className="popular-badge">★ Most Popular</span><span className="popular-duration">{duration}</span></div><div className="popular-package-content"><h3>{name}</h3><p>{route}</p><div className="popular-actions"><a href="tel:+918688624758"><Phone size={14}/> Call Now</a><a href={`https://wa.me/918688624758?text=${encodeURIComponent(`Hi, I want to book ${name}`)}`} target="_blank" rel="noreferrer" className="whatsapp"><MessageCircle size={14}/> WhatsApp</a><Link to={details} className="details">Details <ArrowRight size={14}/></Link></div></div></motion.article>)}</div></section>}
