import React from 'react';
import { createRoot } from 'react-dom/client';
import { BrowserRouter } from 'react-router-dom';
import App from './App';
import './style.css';
import './home-card-alignment.css';
import './package-showcase.css';
import './site-interaction.css';
import './sacred-coverflow-bootstrap.jsx';
import './sacred-coverflow-depth.css';
import './sacred-coverflow-alignment.css';
import './sacred-coverflow-mobile.css';
import './home-normal-sliders.css';
createRoot(document.getElementById('root')).render(<BrowserRouter><App/></BrowserRouter>);
